package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/LLM-4-People/millivolt/internal/config"
)

func TestImageIdentityBoundary(t *testing.T) {
	for _, value := range []string{"millivolt:main", "--privileged", "sha256:abc", "sha256:" + strings.Repeat("G", 64)} {
		if imageID.MatchString(value) {
			t.Fatalf("accepted nonlocal image identity %q", value)
		}
	}
	if !imageID.MatchString("sha256:" + strings.Repeat("a", 64)) {
		t.Fatal("rejected image ID")
	}
}
func TestProbeRejectsHostBeforeHTTP(t *testing.T) {
	t.Setenv(smokeEnv, "")
	if err := probe("seed"); err == nil {
		t.Fatal("host probe accepted")
	}
	if err := probe("unknown"); err == nil {
		t.Fatal("unknown phase accepted")
	}
}
func TestDockerGoVersionMatchesModule(t *testing.T) {
	root := filepath.Join("..", "..")
	dockerfile, err := os.ReadFile(filepath.Join(root, "Dockerfile"))
	if err != nil {
		t.Fatal(err)
	}
	gomod, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatal(err)
	}
	tag := regexp.MustCompile(`(?m)^FROM --platform=\$BUILDPLATFORM golang:([0-9]+\.[0-9]+\.[0-9]+)-[^@]+@sha256:[a-f0-9]{64} AS build$`).FindSubmatch(dockerfile)
	version := regexp.MustCompile(`(?m)^go ([0-9]+\.[0-9]+\.[0-9]+)$`).FindSubmatch(gomod)
	if len(tag) != 2 || len(version) != 2 || string(tag[1]) != string(version[1]) {
		t.Fatal("Docker Go toolchain must match go.mod and retain its digest pin")
	}
	if !strings.Contains(string(dockerfile), "$(go list -m).revisionOverride=") {
		t.Fatal("linker namespace must follow the module owner")
	}
	if !strings.Contains(string(dockerfile), `-ldflags="-s `) {
		t.Fatal("runtime binary must omit optional symbol/debug tables")
	}
	if !strings.Contains(string(dockerfile), "COPY --chown=65532:65532 --chmod=0600 proxy.example.yaml /config/proxy.yaml\n") {
		t.Fatal("image must seed the generated example as private runtime-owned configuration")
	}
}

func TestExampleConfigChecks(t *testing.T) {
	var generated bytes.Buffer
	if err := config.WriteYAML(&generated, config.Example()); err != nil {
		t.Fatal(err)
	}
	if err := checkConfigYAML(generated.Bytes(), config.Example()); err != nil {
		t.Fatal(err)
	}
	if err := checkConfigYAML(generated.Bytes(), config.Default()); err == nil {
		t.Fatal("example accepted as provider-neutral defaults")
	}
	data, err := json.Marshal(config.Example().Map())
	if err != nil {
		t.Fatal(err)
	}
	var values map[string]any
	if err := json.Unmarshal(data, &values); err != nil {
		t.Fatal(err)
	}
	if err := checkExampleProviders(settings{Values: values, Effective: values}); err != nil {
		t.Fatal(err)
	}
	for _, missing := range []settings{{Values: values}, {Effective: values}, {}} {
		if err := checkExampleProviders(missing); err == nil {
			t.Fatal("missing saved or effective provider profiles accepted")
		}
	}
	path := filepath.Join(t.TempDir(), "proxy.yaml")
	if err := os.WriteFile(path, generated.Bytes(), 0o600); err != nil {
		t.Fatal(err)
	}
	if got, err := readPrivateConfig(path); err != nil || !bytes.Equal(got, generated.Bytes()) {
		t.Fatalf("private config rejected: %v", err)
	}
	if err := os.Chmod(path, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := readPrivateConfig(path); err == nil {
		t.Fatal("readable-by-others config accepted")
	}
	link := filepath.Join(t.TempDir(), "proxy.yaml")
	if err := os.Symlink(path, link); err != nil {
		t.Fatal(err)
	}
	if _, err := readPrivateConfig(link); err == nil {
		t.Fatal("symlink config accepted")
	}
}

func TestDockerContextPolicy(t *testing.T) {
	root := filepath.Join("..", "..")
	data, err := os.ReadFile(filepath.Join(root, ".dockerignore"))
	if err != nil {
		t.Fatal(err)
	}
	rules := []string{}
	for line := range strings.SplitSeq(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "#") {
			rules = append(rules, line)
		}
	}
	if len(rules) == 0 || rules[0] != "**" {
		t.Fatal("Docker context must deny by default")
	}
	allowed := map[string]bool{}
	// Source roots are deliberately explicit: new dependencies need review before
	// their entire subtree can be transmitted to a local or remote builder.
	for _, path := range []string{"Dockerfile", ".dockerignore", "go.mod", "go.sum", "VERSION", "version.go", "LICENSE", "THIRD_PARTY_NOTICES.md", "proxy.example.yaml", "cmd/", "cmd/proxy/", "cmd/proxy/**", "internal/", "internal/**", "scripts/", "scripts/licenses/", "scripts/licenses/**"} {
		allowed["!"+path] = true
	}
	finalExclusions := map[string]bool{}
	excluding := false
	for _, rule := range rules[1:] {
		if strings.HasPrefix(rule, "!") {
			if excluding || !allowed[rule] {
				t.Fatalf("unreviewed or late source inclusion %q", rule)
			}
		} else {
			excluding = true
			finalExclusions[rule] = true
		}
	}
	// Git's own metadata is implicitly hidden from publication, but Docker must
	// exclude it explicitly even beneath an allowed source tree.
	if !finalExclusions["**/.git"] {
		t.Error("Docker context must exclude nested Git metadata")
	}
	gitignore, err := os.ReadFile(filepath.Join(root, ".gitignore"))
	if err != nil {
		t.Fatal(err)
	}
	// The existing repository ignore policy owns sensitive suffixes. Mirror all
	// unanchored exclusions, including nested private files in allowed source.
	for line := range strings.SplitSeq(string(gitignore), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.ContainsAny(line[:1], "#!/") {
			continue
		}
		if !finalExclusions["**/"+line] {
			t.Errorf("Docker context lacks nested exclusion for %q", line)
		}
	}
}

func TestLocalDaemonPinsEffectiveContext(t *testing.T) {
	dir := t.TempDir()
	tool := filepath.Join(dir, "docker")
	const fixture = `#!/bin/sh
if [ "$1 $2" = "context inspect" ]; then
  printf '%s\n' "$FIXTURE_ENDPOINT"
else
  [ "$1" = --host ] && [ "$2" = unix:///fixture.sock ] || exit 20
  [ -z "$DOCKER_HOST$DOCKER_CONTEXT$DOCKER_TLS_VERIFY" ] || exit 21
  printf 'pinned\n'
fi
`
	if err := os.WriteFile(tool, []byte(fixture), 0700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("DOCKER_HOST", "unix:///fixture.sock")
	t.Setenv("DOCKER_CONTEXT", "selected")
	t.Setenv("DOCKER_TLS_VERIFY", "1")
	t.Setenv("FIXTURE_ENDPOINT", "ssh://remote.example")
	if _, err := localDaemon(context.Background()); err == nil {
		t.Fatal("DOCKER_HOST hid a remote DOCKER_CONTEXT")
	}
	t.Setenv("FIXTURE_ENDPOINT", "unix:///fixture.sock")
	d, err := localDaemon(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	t.Setenv("DOCKER_CONTEXT", "changed-after-verification")
	got, err := d.command(context.Background(), "image", "inspect")
	if err != nil || string(got) != "pinned" {
		t.Fatalf("endpoint was not pinned: %s %v", got, err)
	}
	t.Setenv("DOCKER_CONTEXT", "")
	for _, bad := range []string{"unix://remote/socket", "unix:relative", "unix:///socket?x=y", "tcp://127.0.0.1:2375"} {
		t.Setenv("DOCKER_HOST", bad)
		if _, err := localDaemon(context.Background()); err == nil {
			t.Errorf("accepted endpoint %q", bad)
		}
	}
}

func TestComposeIsolationContract(t *testing.T) {
	const normal = `{"name":"millivolt","services":{"millivolt":{"image":"released","read_only":true,"ports":[{"host_ip":"127.0.0.1","published":"8080","target":8080}],"volumes":[{"type":"volume","source":"data","target":"/data"},{"type":"volume","source":"config","target":"/config"}]}},"volumes":{"data":{"name":"millivolt_data"},"config":{"name":"millivolt_config"}}}`
	dev := strings.NewReplacer(`"name":"millivolt"`, `"name":"millivolt-dev"`,
		`"image":"released"`, `"image":"built","build":{"context":"/fixture"},"pull_policy":"build"`,
		`"published":"8080"`, `"published":"8081"`, `millivolt_data`, `millivolt-dev_data`, `millivolt_config`, `millivolt-dev_config`).Replace(normal)
	if err := validateCompose([]byte(normal), []byte(dev)); err != nil {
		t.Fatal(err)
	}
	for _, bad := range []string{
		strings.Replace(normal, `"read_only":true`, `"read_only":false`, 1),
		strings.Replace(normal, "127.0.0.1", "0.0.0.0", 1),
		strings.Replace(normal, `"type":"volume"`, `"type":"bind"`, 1),
		strings.Replace(normal, `"target":"/config"`, `"target":"/data"`, 1),
		strings.Replace(normal, `"image":"released"`, `"image":"released","build":{"context":"."}`, 1),
		`{"services":{}}`, `null`, `invalid`,
	} {
		if err := validateCompose([]byte(bad), []byte(dev)); err == nil {
			t.Errorf("accepted unsafe Compose model %s", bad)
		}
	}
	for _, bad := range []string{
		strings.Replace(dev, `"build":{"context":"/fixture"},`, "", 1),
		strings.Replace(dev, `"pull_policy":"build"`, `"pull_policy":"always"`, 1),
		strings.Replace(dev, `"published":"8081"`, `"published":"8080"`, 1),
		strings.Replace(dev, `"name":"millivolt-dev"`, `"name":"millivolt"`, 1),
		strings.Replace(dev, `millivolt-dev_data`, `millivolt_data`, 1),
		strings.Replace(dev, `"ports":[`, `"ports":[{"host_ip":"127.0.0.1","published":"8080","target":8080},`, 1),
	} {
		if err := validateCompose([]byte(normal), []byte(bad)); err == nil {
			t.Errorf("accepted unsafe development Compose model %s", bad)
		}
	}
}

func TestInstalledComposeFiles(t *testing.T) {
	if _, err := exec.LookPath("docker"); err != nil {
		t.Skip("Docker CLI is optional for core checks; container mode requires it")
	}
	if err := exec.Command("docker", "compose", "version").Run(); err != nil {
		t.Skip("Compose plugin is optional for core checks; container mode requires it")
	}
	t.Chdir(filepath.Join("..", ".."))
	t.Setenv("COMPOSE_PROJECT_NAME", "must-not-use")
	t.Setenv("COMPOSE_FILE", "/must-not-read.yaml")
	t.Setenv("MILLIVOLT_IMAGE", "must-not-use")
	t.Setenv("MILLIVOLT_DEV_PORT", "8080")
	// `config` must be daemon-free, so even an unavailable Unix socket works.
	d := dockerCLI{endpoint: "unix:///millivolt-compose-config-test.sock", env: os.Environ()}
	if err := d.checkCompose(t.Context()); err != nil {
		t.Fatal(err)
	}
}

func TestDockerArchiveRoundTripKeepsBinaryBytesAndOwnershipFlag(t *testing.T) {
	dir := t.TempDir()
	tool := filepath.Join(dir, "docker")
	const fixture = `#!/bin/sh
[ "$1" = --host ] && [ "$2" = unix:///fixture.sock ] && [ "$3" = cp ] || exit 20
if [ "$4" = source:/data/. ] && [ "$5" = - ]; then
  printf 'export diagnostic only\n' >&2
  cat "$FIXTURE_SOURCE"
elif [ "$4" = --archive ] && [ "$5" = - ] && [ "$6" = restored:/data ]; then
  printf 'restore diagnostic only\n' >&2
  cat > "$FIXTURE_RESTORED"
else
  exit 21
fi
`
	if err := os.WriteFile(tool, []byte(fixture), 0700); err != nil {
		t.Fatal(err)
	}
	data := []byte(" \t\x00fixture binary payload\xff\x00\n\t ")
	source, restored := filepath.Join(dir, "source"), filepath.Join(dir, "restored")
	if err := os.WriteFile(source, data, 0600); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("FIXTURE_SOURCE", source)
	t.Setenv("FIXTURE_RESTORED", restored)
	d := dockerCLI{endpoint: "unix:///fixture.sock", env: os.Environ()}
	archive := filepath.Join(dir, "backup.tar")
	if err := d.copyVolumeArchive(t.Context(), "source", "restored", "/data", archive); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{archive, restored} {
		got, err := os.ReadFile(path)
		if err != nil || !bytes.Equal(got, data) {
			t.Fatalf("binary stream changed at %s: %x %v", path, got, err)
		}
	}
	info, err := os.Stat(archive)
	if err != nil || info.Mode().Perm() != 0600 {
		t.Fatalf("archive is not private: %v %v", info, err)
	}
	if err := d.copyVolumeArchive(t.Context(), "source", "restored", "/data", archive); !errors.Is(err, os.ErrExist) {
		t.Fatalf("existing archive overwrite was not rejected: %v", err)
	}
	link := filepath.Join(dir, "alias.tar")
	if err := os.Symlink(archive, link); err != nil {
		t.Fatal(err)
	}
	if err := d.copyVolumeArchive(t.Context(), "source", "restored", "/data", link); !errors.Is(err, os.ErrExist) {
		t.Fatalf("archive symlink was not rejected: %v", err)
	}
}

func TestDockerBinaryFailureDoesNotExposeArchiveInError(t *testing.T) {
	dir := t.TempDir()
	tool := filepath.Join(dir, "docker")
	const fixture = "#!/bin/sh\nprintf 'archive-secret-payload'\nprintf 'fixture command failed' >&2\nexit 17\n"
	if err := os.WriteFile(tool, []byte(fixture), 0700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	var output bytes.Buffer
	_, err := dockerCommandIO(t.Context(), os.Environ(), nil, &output, "cp", "source:/config/.", "-")
	if err == nil || !strings.Contains(err.Error(), "fixture command failed") || strings.Contains(err.Error(), "archive-secret-payload") {
		t.Fatalf("binary failure mixed streams: %v", err)
	}
	if output.String() != "archive-secret-payload" {
		t.Fatalf("stdout changed: %q", output.String())
	}
	ctx, cancel := context.WithCancel(t.Context())
	cancel()
	if _, err := dockerCommandIO(ctx, os.Environ(), nil, io.Discard, "cp", "source:/config/.", "-"); !errors.Is(err, context.Canceled) {
		t.Fatalf("canceled archive command started: %v", err)
	}
}

func TestDockerTextCommandsRetainStderrLogs(t *testing.T) {
	dir := t.TempDir()
	tool := filepath.Join(dir, "docker")
	if err := os.WriteFile(tool, []byte("#!/bin/sh\nprintf 'runtime log on stderr\\n' >&2\n"), 0700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	logs, err := dockerCommand(t.Context(), os.Environ(), "logs", "owned")
	if err != nil || string(logs) != "runtime log on stderr" {
		t.Fatalf("stderr-only container logs were lost: %s %v", logs, err)
	}
}

func TestBackupRequiresSuccessfulStoppedState(t *testing.T) {
	dir := t.TempDir()
	tool := filepath.Join(dir, "docker")
	const fixture = `#!/bin/sh
[ "$1" = --host ] && [ "$2" = unix:///fixture.sock ] || exit 20
case "$3" in
  stop) [ "$4" = --time ] && [ "$5" = 30 ] && [ "$6" = owned ] || exit 21 ;;
  inspect) printf '%s\n' "$FIXTURE_STATE" ;;
  *) exit 22 ;;
esac
`
	if err := os.WriteFile(tool, []byte(fixture), 0700); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
	for _, state := range []string{"exited 0", "running 0", "exited 137", "created 0", ""} {
		t.Setenv("FIXTURE_STATE", state)
		d := dockerCLI{endpoint: "unix:///fixture.sock", env: os.Environ()}
		if err := d.stopClean(t.Context(), "owned"); (err == nil) != (state == "exited 0") {
			t.Errorf("state %q: %v", state, err)
		}
	}
}
